server.port=8080

spring.profiles.active=@activatedProperties@
#security
application.security.jwt.secret-key=586E3272357538782F413F4428472B4B6250655368566B597033733676397924
application.security.jwt.expiration=604800000
application.security.jwt.refresh-token.expiration=604800000
#application.security.jwt.expiration=20000

#DATA
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

# Cors
security.allowedOrigins=${PROD_ALLOWED_ORIGINS:*}